import { NextApiRequest, NextApiResponse } from 'next';
import axios from 'axios';
import * as cheerio from 'cheerio';

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') {
      return res.status(405).json({ success: false, error: 'Method not allowed' });
        }

          const { url } = req.body;

            if (!url) {
                return res.status(400).json({ success: false, error: 'URL is required' });
                  }

                    try {
                        // Clean and validate URL
                            const cleanUrl = url.trim();
                                if (!cleanUrl.includes('tiktok.com')) {
                                      return res.status(400).json({ success: false, error: 'URL TikTok tidak valid' });
                                          }

                                              // Add headers to mimic browser request
                                                  const headers = {
                                                        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
                                                              'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
                                                                    'Accept-Language': 'en-US,en;q=0.5',
                                                                          'Accept-Encoding': 'gzip, deflate, br',
                                                                                'DNT': '1',
                                                                                      'Connection': 'keep-alive',
                                                                                            'Upgrade-Insecure-Requests': '1',
                                                                                                  'Sec-Fetch-Dest': 'document',
                                                                                                        'Sec-Fetch-Mode': 'navigate',
                                                                                                              'Sec-Fetch-Site': 'none',
                                                                                                                    'Cache-Control': 'max-age=0'
                                                                                                                        };

                                                                                                                            // Fetch the TikTok page
                                                                                                                                const response = await axios.get(cleanUrl, { headers, timeout: 10000 });
                                                                                                                                    const html = response.data;
                                                                                                                                        const $ = cheerio.load(html);

                                                                                                                                            // Try to extract data from JSON-LD
                                                                                                                                                let videoData: any = null;
                                                                                                                                                    $('script[type="application/ld+json"]').each((_, element) => {
                                                                                                                                                          try {
                                                                                                                                                                  const json = JSON.parse($(element).html() || '{}');
                                                                                                                                                                          if (json['@type'] === 'VideoObject') {
                                                                                                                                                                                    videoData = json;
                                                                                                                                                                                            }
                                                                                                                                                                                                  } catch (e) {
                                                                                                                                                                                                          // Continue if JSON parsing fails
                                                                                                                                                                                                                }
                                                                                                                                                                                                                    });

                                                                                                                                                                                                                        // Alternative method: Look for video URL in meta tags and scripts
                                                                                                                                                                                                                            let videoUrl = '';
                                                                                                                                                                                                                                let audioUrl = '';
                                                                                                                                                                                                                                    let thumbnailUrl = '';
                                                                                                                                                                                                                                        let duration = 0;

                                                                                                                                                                                                                                            // Method 1: Look in meta tags
                                                                                                                                                                                                                                                videoUrl = $('meta[property="og:video"]').attr('content') || 
                                                                                                                                                                                                                                                               $('meta[property="og:video:url"]').attr('content') || 
                                                                                                                                                                                                                                                                              $('meta[name="twitter:player:stream"]').attr('content') || '';

                                                                                                                                                                                                                                                                                  thumbnailUrl = $('meta[property="og:image"]').attr('content') || 
                                                                                                                                                                                                                                                                                                     $('meta[name="twitter:image"]').attr('content') || '';

                                                                                                                                                                                                                                                                                                         // Method 2: Look in script tags for JSON data
                                                                                                                                                                                                                                                                                                             if (!videoUrl) {
                                                                                                                                                                                                                                                                                                                   const scriptTags = $('script');
                                                                                                                                                                                                                                                                                                                         for (let i = 0; i < scriptTags.length; i++) {
                                                                                                                                                                                                                                                                                                                                 const scriptContent = $(scriptTags[i]).html();
                                                                                                                                                                                                                                                                                                                                         if (scriptContent && scriptContent.includes('playAddr')) {
                                                                                                                                                                                                                                                                                                                                                   const matches = scriptContent.match(/"playAddr":"(.*?)"/);
                                                                                                                                                                                                                                                                                                                                                             if (matches && matches[1]) {
                                                                                                                                                                                                                                                                                                                                                                         videoUrl = matches[1].replace(/\\u0026/g, '&');
                                                                                                                                                                                                                                                                                                                                                                                     break;
                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                 }

                                                                                                                                                                                                                                                                                                                                                                                                                     // Method 3: Look for audio data
                                                                                                                                                                                                                                                                                                                                                                                                                         const audioScripts = $('script');
                                                                                                                                                                                                                                                                                                                                                                                                                             for (let i = 0; i < audioScripts.length; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                   const scriptContent = $(audioScripts[i]).html();
                                                                                                                                                                                                                                                                                                                                                                                                                                         if (scriptContent && scriptContent.includes('playUrl')) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                 const audioMatch = scriptContent.match(/"playUrl":"(.*?)"/);
                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (audioMatch && audioMatch[1]) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   audioUrl = audioMatch[1].replace(/\\u0026/g, '&');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // If still no video URL, try alternative API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if (!videoUrl) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   videoUrl = await tryAlternativeAPI(cleanUrl);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           if (!videoUrl && !audioUrl) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return res.status(404).json({ success: false, error: 'Tidak dapat menemukan media dari URL tersebut' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // Determine content type
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             let type: 'video' | 'image' | 'audio' = 'video';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 if (videoUrl) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       type = 'video';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           } else if (audioUrl) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 type = 'audio';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     } else if (thumbnailUrl) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           type = 'image';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   // Get final download URL
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       const downloadUrl = type === 'video' ? videoUrl : type === 'audio' ? audioUrl : thumbnailUrl;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           // Validate download URL
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               if (!downloadUrl) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     return res.status(404).json({ success: false, error: 'URL download tidak ditemukan' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             res.json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   success: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         data: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 type,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         url: downloadUrl,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 thumbnail: thumbnailUrl || undefined,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         title: videoData?.name || 'TikTok Video',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 duration: videoData?.duration || duration
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             } catch (error: any) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 console.error('Download error:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (error.code === 'ENOTFOUND') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               return res.status(500).json({ success: false, error: 'Tidak dapat terhubung ke TikTok' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           if (error.response?.status === 404) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return res.status(404).json({ success: false, error: 'Video tidak ditemukan atau telah dihapus' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         res.status(500).json({ 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               success: false, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     error: 'Terjadi kesalahan saat memproses video: ' + error.message 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           // Alternative method using TikTok APIs
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           async function tryAlternativeAPI(url: string): Promise<string> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // Method 1: Use ssstik.io API
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const ssstikResponse = await axios.post('https://ssstik.io/abc?url=dl', 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           new URLSearchParams({ id: url, locale: 'id', tt: 'your_tt_token_here' }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         headers: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   'Content-Type': 'application/x-www-form-urlencoded',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   const ssstikHtml = ssstikResponse.data;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       const $ = cheerio.load(ssstikHtml);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           const downloadLink = $('a[download]').attr('href');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   if (downloadLink) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         return downloadLink.startsWith('http') ? downloadLink : `https://ssstik.io${downloadLink}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   console.log('Alternative API failed:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       return '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }